theme: jekyll-theme-slate
title: Jiachi Chen(陈嘉弛)
Ph.D Candidate, Faculty of Information Technology, Monash University
Email: Jiachi.chen@monash.edu
About me: I am a second year Ph.D student with Australian Government RTP Scholarship at the Faculty of Information Technology, Monash University, Australia. I am honored and fortunate to be supervised by Dr.Xin Xia and Prof.John Grundy. Prior to joining Monash University, I spent two years at the Hong Kong Polytechnic University, under the supervision of Dr. Daniel Xiapu Luo. My research interests include mining software repository, software security, and smart contract analysis.
